import type { Metadata } from "next";
import { Baloo_Bhai_2, Phudu } from 'next/font/google';
import "./globals.css";


const balooBhai2 = Baloo_Bhai_2({
  subsets: ['vietnamese'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-baloo-bhai-2', 
});

const phudu = Phudu({
  subsets: ['vietnamese'],
  weight: '700', // Chỉ định trọng lượng cụ thể
  variable: '--font-phudu', // Đặt biến CSS cho font này
});


export const metadata: Metadata = {
  title: "Tâm Đức Cường",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${balooBhai2.variable} ${phudu.variable}`}>
      <head>
        <meta name="google-site-verification" content="7lf1VdNiAhsfiklzsWWWOtWtMAFNWrsOMFIu0LtRuwk" />
      </head>
      <body
        className={`${balooBhai2.variable} ${phudu.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
